export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const SEARCH_ARTISTS_DONE = 'SEARCH_ARTISTS_DONE';
export const SEARCH_ARTISTS_FAIL = 'SEARCH_ARTISTS_FAIL';

export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const FETCH_ALBUMS_DONE = 'FETCH_ALBUMS_DONE';
export const FETCH_ALBUMS_FAIL = 'FETCH_ALBUMS_FAIL';

export const FETCH_LIKED_ALBUMS = 'FETCH_LIKED_ALBUMS';
export const FETCH_LIKED_ALBUMS_DONE = 'FETCH_LIKED_ALBUMS_DONE';
export const FETCH_LIKED_ALBUMS_FAIL = 'FETCH_LIKED_ALBUMS_FAIL';

export const FETCH_ALBUM_DETAIL = 'FETCH_ALBUM_DETAIL';
export const FETCH_ALBUM_DETAIL_DONE = 'FETCH_ALBUM_DETAIL_DONE';
export const FETCH_ALBUM_DETAIL_FAIL = 'FETCH_ALBUM_DETAIL_FAIL';

export const TOGGLE_ALBUM_LIKE = 'TOGGLE_ALBUM_LIKE';

export const DISMISS_ERROR_MESSAGE = 'DISMISS_ERROR_MESSAGE';
